from __future__ import annotations

from ._util import (
    JOB_RECORD_SUFFIXES,
    PROFILE_SOURCE_SUFFIXES,
    TEXT_PREVIEW_SUFFIXES,
    format_user_path,
    resolve_workspace_input_path,
    resolve_workspace_output_path,
)
from .documents import (
    BuildCoverLetterResult,
    BuildResumeTailoredDraftResult,
    BuildResumeTailoringPlanResult,
    CompareCoverLettersResult,
    CoverLetterDraftArtifact,
    build_cover_letter_compare_view,
    build_cover_letter_form_view,
    build_cover_letter_selection_context,
    build_resume_tailored_draft_form_view,
    build_resume_tailoring_form_view,
    run_cover_letter_build,
    run_cover_letter_compare,
    run_resume_tailored_draft_build,
    run_resume_tailoring_plan_build,
)
from .jobs import (
    BuildRerankJobsResult,
    build_latest_rankings_view,
    build_rerank_jobs_form_view,
    run_rerank_jobs_build,
)
from .profile import (
    BuildProfileResult,
    build_profile_form_view,
    run_profile_build,
)
from .runs import (
    ArtifactPreview,
    build_artifact_preview,
    build_dashboard_view,
    build_run_detail_view,
    build_runs_view,
)
from .setup import (
    JOB_SOURCE_TYPES,
    BuildRefreshJobsResult,
    PullOllamaModelsResult,
    SaveAdzunaCredentialsResult,
    SaveJobSourceConfigResult,
    build_job_sources_view,
    build_ollama_setup_view,
    run_adzuna_credentials_save,
    run_job_source_delete,
    run_job_source_save,
    run_job_source_toggle,
    run_local_ollama_runtime_install,
    run_ollama_models_pull,
    run_ollama_server_restart,
    run_refresh_jobs_build,
)

__all__ = [
    # Constants
    "TEXT_PREVIEW_SUFFIXES",
    "PROFILE_SOURCE_SUFFIXES",
    "JOB_RECORD_SUFFIXES",
    "JOB_SOURCE_TYPES",
    # Dataclasses
    "ArtifactPreview",
    "BuildProfileResult",
    "BuildCoverLetterResult",
    "CoverLetterDraftArtifact",
    "CompareCoverLettersResult",
    "BuildResumeTailoringPlanResult",
    "BuildResumeTailoredDraftResult",
    "BuildRerankJobsResult",
    "SaveAdzunaCredentialsResult",
    "BuildRefreshJobsResult",
    "SaveJobSourceConfigResult",
    "PullOllamaModelsResult",
    # View builders
    "build_dashboard_view",
    "build_runs_view",
    "build_run_detail_view",
    "build_artifact_preview",
    "build_profile_form_view",
    "build_latest_rankings_view",
    "build_rerank_jobs_form_view",
    "build_job_sources_view",
    "build_ollama_setup_view",
    "build_cover_letter_form_view",
    "build_cover_letter_compare_view",
    "build_cover_letter_selection_context",
    "build_resume_tailoring_form_view",
    "build_resume_tailored_draft_form_view",
    # Action runners
    "run_profile_build",
    "run_adzuna_credentials_save",
    "run_ollama_models_pull",
    "run_local_ollama_runtime_install",
    "run_ollama_server_restart",
    "run_job_source_save",
    "run_job_source_delete",
    "run_job_source_toggle",
    "run_refresh_jobs_build",
    "run_cover_letter_build",
    "run_cover_letter_compare",
    "run_resume_tailoring_plan_build",
    "run_resume_tailored_draft_build",
    "run_rerank_jobs_build",
    # Utilities
    "resolve_workspace_input_path",
    "resolve_workspace_output_path",
    "format_user_path",
]
